# Generated by Django 4.1 on 2022-08-23 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('header', models.ImageField(blank=True, default='default.jfif', upload_to='')),
                ('genre', models.CharField(max_length=100)),
                ('sub_header', models.ImageField(blank=True, default='default.jfif', upload_to='')),
                ('cast', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, default='default.jfif', upload_to='')),
                ('year', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
