# Generated by Django 4.1 on 2022-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Film Title', max_length=100),
        ),
    ]
