# Generated by Django 4.1 on 2022-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.CharField(default='anonymus', max_length=100),
        ),
    ]
